import Link from "next/link";
import { ArrowRight, BadgeCheck, CalendarDays, Check, ChevronRight, MapPin, ShieldCheck, Star, Users } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/shared/components/site-header";
import { UiState } from "@/shared/components/ui-state";
import { getCategories, getVendors } from "@backend/vendors/queries";
import { getLiveEvents } from "@backend/events/queries";
import { formatRating, formatXaf } from "@/shared/lib/format";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [featured, categories, liveEvents] = await Promise.all([getVendors({ featured: true }), getCategories(), getLiveEvents()]);
  return <main>
    <section className="relative min-h-[700px] overflow-hidden bg-ink text-white">
      <SiteHeader dark />
      <div className="absolute inset-y-0 right-0 w-full opacity-35 md:w-[53%] md:opacity-70"><img src="https://images.pexels.com/photos/37828118/pexels-photo-37828118.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1100&w=1100" alt="Elegant outdoor celebration" className="size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/45 to-transparent" /></div>
      <div className="container-shell relative flex min-h-[620px] items-center py-20"><div className="max-w-3xl"><p className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/7 px-3 py-2 text-xs text-white/72"><span className="size-1.5 rounded-full bg-marigold" />Verified event professionals · Cameroon</p><h1 className="display text-[clamp(3.5rem,8vw,7rem)] font-semibold leading-[.88] tracking-[-.065em]">The right people<br /><span className="text-marigold">meet the right place.</span></h1><p className="mt-8 max-w-xl text-[1.05rem] leading-8 text-white/68">Discover trusted vendors, book with protected payments, and stay present for the celebration.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/vendors" className="btn-primary">Explore trusted vendors <ArrowRight size={17} /></Link><Link href="#how-it-works" className="btn-secondary !border-white/20 !bg-white/8 !text-white">See how it works</Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/12 pt-6 text-xs text-white/48"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-marigold" />Escrow-protected</span><span className="flex items-center gap-2"><BadgeCheck size={15} className="text-marigold" />Manually verified</span><span className="flex items-center gap-2"><MapPin size={15} className="text-marigold" />Made for Cameroon</span></div></div></div>
    </section>
    <section className="border-b border-ink/10 bg-marigold py-4"><div className="container-shell flex flex-wrap justify-center gap-x-10 gap-y-2 text-xs font-bold uppercase tracking-[.1em] text-ink/75"><span>Verified identities</span><span>Protected mobile money</span><span>Clear dispute support</span><span>Human trust team</span></div></section>
    <section className="py-24 sm:py-32"><div className="container-shell"><div className="flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-berry">Find your people</p><h2 className="display mt-4 text-5xl font-semibold leading-[.98] sm:text-6xl">Every detail deserves<br />a trusted hand.</h2></div><Link href="/vendors" className="flex items-center gap-2 text-sm font-bold">Browse all categories <ArrowRight size={16} /></Link></div><div className="mt-12 grid grid-cols-2 gap-px overflow-hidden rounded-[22px] border border-ink/12 bg-ink/12 md:grid-cols-5">{categories.length ? categories.slice(0, 5).map((category) => <Link href={`/vendors?category=${category.slug}`} key={category.id} className="group min-h-40 bg-paper p-6 transition hover:bg-white"><Users size={20} className="text-berry" /><p className="display mt-9 text-xl font-semibold">{category.name}</p><span className="mt-3 flex items-center gap-1 text-[11px] font-bold text-ink/42">Explore <ChevronRight size={12} /></span></Link>) : <UiState className="col-span-full" title="Categories are being curated" description="Our marketplace team is preparing the first collection." />}</div></div></section>
    <section className="bg-[#e9e2d5] py-24 sm:py-32"><div className="container-shell"><p className="eyebrow text-berry">Curated for quality</p><h2 className="display mt-4 text-5xl font-semibold sm:text-6xl">Professionals worth meeting.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{featured.length ? featured.slice(0, 3).map((vendor) => <Link href={`/vendors/${vendor.slug}`} key={vendor.id} className="group overflow-hidden rounded-[20px] bg-white shadow-[0_18px_50px_rgba(23,35,31,.08)]"><div className="relative aspect-[4/3] overflow-hidden"><img src={vendor.imageUrl} alt={vendor.businessName} className="size-full object-cover transition duration-700 group-hover:scale-[1.04]" /><span className="absolute left-4 top-4 inline-flex items-center gap-1.5 rounded-full bg-white/92 px-3 py-1.5 text-[10px] font-bold"><BadgeCheck size={13} className="text-forest" />VERIFIED</span></div><div className="p-5"><div className="flex justify-between gap-4"><div><p className="display text-2xl font-semibold">{vendor.businessName}</p><p className="mt-1 text-xs text-ink/52">{vendor.categories.map((category) => category.name).join(" · ")}</p></div><span className="flex items-center gap-1 text-xs font-bold"><Star size={13} fill="currentColor" className="text-marigold" />{formatRating(vendor.rating)}</span></div><div className="mt-5 flex justify-between border-t border-ink/10 pt-4 text-xs text-ink/53"><span className="flex items-center gap-1"><MapPin size={13} />{vendor.city}</span><strong>{formatXaf(vendor.startingPrice)}</strong></div></div></Link>) : <UiState className="md:col-span-3" title="Our first vendors are on their way" description="We’re reviewing every profile before it appears." />}</div><div className="mt-10 text-center"><Link href="/vendors" className="btn-ink">View the marketplace <ArrowRight size={16} /></Link></div></div></section>
    <section id="trust" className="dark-grid scroll-mt-24 py-24 text-white sm:py-32"><div id="how-it-works" className="container-shell grid gap-12 lg:grid-cols-2"><div><p className="eyebrow text-marigold">Trust in every booking</p><h2 className="display mt-5 text-5xl font-semibold leading-[.98] sm:text-6xl">Pay with confidence.<br />Celebrate at ease.</h2><p className="mt-6 max-w-xl text-[15px] leading-8 text-white/58">Your payment is held securely while the work happens, then released when the service is complete.</p></div><div className="grid gap-px overflow-hidden rounded-[22px] border border-white/14 bg-white/14 sm:grid-cols-3">{[["01","Discover","Find trusted people for every detail."],["02","Book protected","Secure your payment with confidence."],["03","Celebrate","Approve delivery and enjoy the moment."]].map(([n,title,copy]) => <div key={n} className="bg-ink p-7"><span className="mono text-xs text-marigold">{n}</span><h3 className="display mt-14 text-3xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-white/56">{copy}</p></div>)}</div></div></section>
    {liveEvents.length > 0 && <section className="py-20"><div className="container-shell"><p className="eyebrow text-berry">Live right now</p><h2 className="display mt-3 text-4xl font-semibold">Ongoing celebrations.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{liveEvents.slice(0, 3).map((event) => <article className="overflow-hidden rounded-2xl border border-ink/10" key={event.id}>{event.coverUrl && <img src={event.coverUrl} alt={event.title} className="aspect-[1.7] w-full object-cover" />}<div className="p-5"><p className="text-xs font-bold text-berry">LIVE</p><h3 className="display mt-2 text-2xl font-semibold">{event.title}</h3><p className="mt-2 flex items-center gap-1 text-xs text-ink/50"><CalendarDays size={13} />{event.city}</p></div></article>)}</div></div></section>}
    <SiteFooter />
  </main>;
}
