import { resolveDispute } from "@backend/disputes/actions";
import { reviewAccessRequest, setServiceProviderVerified } from "@backend/admin/actions";
import { DashboardShell } from "@/shared/components/dashboard-shell";
import { requireRole } from "@backend/auth/session";
import { getAdminData } from "@backend/admin/queries";
import { formatXaf } from "@/shared/lib/format";
import { BadgeCheck, Banknote, Check, CircleAlert, Clock3, FileClock, Scale, ShieldCheck, UserCheck, Users, X } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const session = await requireRole("admin");
  const data = await getAdminData();
  const pending = data.requests.filter((item) => {
    return item.status === "pending";
  });
  const openDisputes = data.disputes.filter((item) => ["open", "under_review"].includes(item.dispute.status));
  return (
    <DashboardShell role="admin" name={session.fullName} active="Command centre">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
        <div><p className="eyebrow text-berry">Trust command centre</p><h1 className="display mt-2 text-4xl font-semibold sm:text-5xl">Every decision leaves a trail.</h1><p className="mt-3 text-sm text-ink/50">Review access, monitor protected value, and resolve exceptions transparently.</p></div>
        <span className="inline-flex items-center gap-2 rounded-full bg-mint px-4 py-2 text-xs font-bold text-forest"><ShieldCheck size={15} />Systems operational</span>
      </div>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl bg-ink p-5 text-white"><div className="flex justify-between"><p className="eyebrow text-white/38">Value protected</p><Banknote className="text-marigold" size={18} /></div><p className="mono mt-6 text-2xl font-semibold">{formatXaf(data.heldAmount)}</p><p className="mt-2 text-[10px] text-white/38">Held, reviewing, or disputed</p></div>
        <div className="rounded-2xl border border-ink/10 bg-marigold p-5"><div className="flex justify-between"><p className="eyebrow text-ink/42">Access queue</p><UserCheck size={18} /></div><p className="display mt-5 text-4xl font-semibold">{pending.length}</p><p className="mt-1 text-[10px] text-ink/43">Need human review</p></div>
        <div className="rounded-2xl border border-ink/10 bg-white p-5"><div className="flex justify-between"><p className="eyebrow text-ink/38">Trusted vendors</p><BadgeCheck className="text-forest" size={18} /></div><p className="display mt-5 text-4xl font-semibold">{data.vendors.filter((item) => item.verified).length}</p><p className="mt-1 text-[10px] text-ink/40">Verified and visible</p></div>
        <div className="rounded-2xl border border-ink/10 bg-white p-5"><div className="flex justify-between"><p className="eyebrow text-ink/38">Open disputes</p><Scale className="text-berry" size={18} /></div><p className="display mt-5 text-4xl font-semibold">{openDisputes.length}</p><p className="mt-1 text-[10px] text-ink/40">Frozen escrow cases</p></div>
      </div>

      <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
        <div className="space-y-6">
          <section id="access" className="rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7">
            <div className="flex items-end justify-between"><div><p className="eyebrow text-berry">Access requests</p><h2 className="display mt-2 text-3xl font-semibold">Who enters the circle.</h2></div><span className="rounded-full bg-marigold/20 px-3 py-1 text-[9px] font-bold">{pending.length} PENDING</span></div>
            <div className="mt-6 divide-y divide-ink/10">{data.requests.length ? data.requests.map((request) => <div key={request.id} className="py-5 first:pt-0 last:pb-0"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-full ${request.status === "approved" ? "bg-mint text-forest" : request.status === "rejected" ? "bg-berry/10 text-berry" : "bg-paper"}`}>{request.status === "approved" ? <Check size={16} /> : request.status === "rejected" ? <X size={16} /> : <Clock3 size={16} />}</span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold">{request.fullName}</p><span className="rounded-full bg-paper px-2 py-1 text-[8px] font-bold uppercase">{request.desiredRole}</span></div><p className="mt-1 text-[10px] text-ink/43">{request.email}</p>{request.message && <p className="mt-2 max-w-lg text-xs leading-5 text-ink/52">“{request.message}”</p>}</div></div>{request.status === "pending" ? <div className="flex gap-2 pl-13 sm:pl-0"><form action={reviewAccessRequest}><input type="hidden" name="id" value={request.id} /><input type="hidden" name="decision" value="approved" /><button className="btn-primary !min-h-9 !px-3 !py-1 text-[10px]"><Check size={13} />Approve</button></form><form action={reviewAccessRequest}><input type="hidden" name="id" value={request.id} /><input type="hidden" name="decision" value="rejected" /><button className="btn-secondary !min-h-9 !px-3 !py-1 text-[10px]"><X size={13} />Reject</button></form></div> : <span className="text-[9px] font-bold uppercase text-ink/35">{request.status}</span>}</div></div>) : <div className="py-12 text-center"><UserCheck className="mx-auto text-ink/25"/><p className="mt-4 text-sm text-ink/50">No access requests yet.</p></div>}</div>
          </section>

          {data.requests.some((request) => request.identityDocumentPath) && <section className="rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7"><p className="eyebrow text-berry">Identity documents</p><h2 className="display mt-2 text-3xl font-semibold">Proof waiting for review.</h2><div className="mt-5 divide-y divide-ink/10">{data.requests.filter((request) => request.identityDocumentPath).map((request) => <div key={request.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-bold">{request.fullName}</p><p className="mt-1 text-[10px] text-ink/45">{request.identityDocumentName} · {request.desiredRole}</p></div><a className="btn-secondary !min-h-9 !px-3 !py-1 text-[10px]" href={`/api/admin/access-requests/${request.id}/document`} target="_blank" rel="noreferrer">View document</a></div>)}</div></section>}

          <section id="disputes" className="rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7">
            <div className="flex items-start justify-between"><div><p className="eyebrow text-berry">Dispute review</p><h2 className="display mt-2 text-3xl font-semibold">Evidence before outcome.</h2></div><Scale className="text-berry" /></div>
            {data.disputes.length ? <div className="mt-6 space-y-5">{data.disputes.map((item) => <div key={item.dispute.id} className="rounded-2xl border border-ink/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-berry/10 px-2.5 py-1 text-[9px] font-bold uppercase text-berry">{item.dispute.status.replaceAll("_", " ")}</span><h3 className="mt-3 text-sm font-bold">{item.dispute.reason}</h3><p className="mono mt-1 text-[9px] text-ink/40">{item.booking.reference} · {formatXaf(item.escrow.amount)}</p></div><FileClock className="text-ink/25" size={19} /></div><p className="mt-4 text-xs leading-6 text-ink/53">{item.dispute.description}</p><div className="mt-5 rounded-xl bg-paper p-4"><p className="eyebrow text-ink/35">Immutable audit trail</p><div className="mt-3 space-y-3">{item.logs.map((log) => <div key={log.id} className="border-l-2 border-marigold pl-3"><p className="text-[10px] font-bold">{log.action.replaceAll("_", " ")}</p><p className="mt-1 text-[9px] leading-4 text-ink/43">{log.details}</p><p className="mono mt-1 text-[8px] text-ink/28">{log.createdAt.toISOString()}</p></div>)}</div></div>{["open", "under_review"].includes(item.dispute.status) && <details className="mt-5"><summary className="cursor-pointer text-xs font-bold text-berry">Record final resolution</summary><form action={resolveDispute} className="mt-4 grid gap-3"><input type="hidden" name="disputeId" value={item.dispute.id} /><select className="select-field" name="decision"><option value="vendor">Release all to vendor</option><option value="organiser">Refund all to organiser</option><option value="split">Partial split</option></select><div className="grid grid-cols-2 gap-3"><label><span className="label-text">Vendor share</span><input className="field" type="number" name="vendorShare" defaultValue={Math.floor(item.escrow.amount / 2)} /></label><label><span className="label-text">Organiser refund</span><input className="field" type="number" name="organiserRefund" defaultValue={item.escrow.amount - Math.floor(item.escrow.amount / 2)} /></label></div><textarea className="textarea-field" name="resolutionNote" placeholder="Explain the evidence and policy basis for this decision…" required /><button className="btn-ink justify-self-start"><Scale size={14} />Commit logged decision</button></form></details>}</div>)}</div> : <div className="mt-6 rounded-2xl bg-mint/50 p-8 text-center"><Check className="mx-auto text-forest" /><p className="mt-3 text-sm font-bold">No disputes awaiting review.</p><p className="mt-1 text-[10px] text-ink/42">New cases will appear with their complete audit trail.</p></div>}
          </section>
        </div>
        <aside className="space-y-6">
          <section id="transactions" className="rounded-[22px] border border-ink/10 bg-white p-5"><p className="eyebrow text-ink/38">Transaction monitor</p><div className="mt-4 divide-y divide-ink/10">{data.bookings.length ? data.bookings.map((booking) => <div key={booking.id} className="py-4"><div className="flex justify-between gap-3"><div><p className="mono text-[10px] font-bold">{booking.reference}</p><p className="mt-1 text-[9px] capitalize text-ink/40">{booking.status.replaceAll("_", " ")}</p></div><p className="mono text-[10px] font-bold">{formatXaf(booking.fundedAmount)}</p></div></div>) : <div className="py-8 text-center text-sm text-ink/50">No transactions yet.</div>}</div></section>
          <section id="vendors" className="rounded-[22px] bg-forest p-5 text-white"><div className="flex items-center justify-between"><p className="eyebrow text-white/40">Vendor trust</p><Users size={17} className="text-marigold" /></div><div className="mt-5 space-y-4">{data.vendors.length ? data.vendors.slice(0, 5).map((vendor) => <div key={vendor.id} className="flex items-center gap-3"><img src={vendor.imageUrl} alt="" className="size-9 rounded-full object-cover" /><div className="min-w-0"><p className="truncate text-xs font-bold">{vendor.businessName}</p><p className="mt-1 text-[8px] text-white/40">{vendor.city} · {vendor.completedEvents} events</p></div><form action={setServiceProviderVerified}><input type="hidden" name="vendorId" value={vendor.id} /><input type="hidden" name="verified" value={vendor.verified ? "false" : "true"} /><button aria-label="Toggle verification" title={vendor.verified ? "Revoke verification" : "Verify vendor"}><BadgeCheck className={vendor.verified ? "text-marigold" : "text-white/25"} size={16} /></button></form></div>) : <p className="py-3 text-xs text-white/45">No vendors yet.</p>}</div></section>
          <section className="rounded-[22px] border border-berry/20 bg-berry/8 p-5"><CircleAlert className="text-berry" size={19} /><p className="mt-4 text-xs font-bold">Trust policy reminder</p><p className="mt-2 text-[10px] leading-5 text-ink/48">Admin outcomes must cite evidence and cancellation policy. Audit records are append-only and never overwritten.</p></section>
        </aside>
      </div>
    </DashboardShell>
  );
}
