import Link from "next/link";
import QRCode from "qrcode";
import { CalendarDays, MapPin, QrCode, ShieldCheck, Ticket } from "lucide-react";
import { DashboardShell } from "@/shared/components/dashboard-shell";
import { BecomeOrganizerForm } from "@/shared/components/become-organizer-form";
import { TicketPurchaseForm } from "@/shared/components/ticket-purchase-form";
import { requireRole } from "@backend/auth/session";
import { getClientData } from "@backend/client/queries";
import { formatXaf } from "@/shared/lib/format";

export const dynamic = "force-dynamic";

export default async function ClientPage() {
  const session = await requireRole("client");
  const data = await getClientData(session.userId);
  const ticketsWithQr = await Promise.all(data.tickets.map(async (row) => ({ ...row, qr: await QRCode.toDataURL(row.ticket.code, { width: 260, margin: 1, color: { dark: "#17231f", light: "#ffffff" } }) })));
  const nextTicket = ticketsWithQr[0];
  return <DashboardShell role="client" name={session.fullName} active="My tickets" allowViewSwitch={session.isOrganizer}>
    {!session.isOrganizer && session.organizerStatus !== "pending" && <section className="rounded-[22px] border border-marigold/30 bg-marigold/10 p-5 sm:p-7"><p className="eyebrow text-berry">Plan an event</p><h2 className="display mt-2 text-3xl font-semibold">Become an organizer.</h2><p className="mt-2 text-sm text-ink/55">Create events, assign trusted providers, and manage bookings from one place.</p><BecomeOrganizerForm fullName={session.fullName} email={session.email} /></section>}
    {!session.isOrganizer && session.organizerStatus === "pending" && <section className="rounded-[22px] border border-marigold/30 bg-marigold/10 p-5 sm:p-7"><p className="eyebrow text-berry">Organizer request</p><h2 className="display mt-2 text-3xl font-semibold">Your request is under review.</h2><p className="mt-2 text-sm text-ink/55">We’ll notify you when you can switch to the organiser workspace.</p></section>}
    <section className="mt-10"><p className="eyebrow text-berry">Client wallet</p><h1 className="display mt-2 text-4xl font-semibold sm:text-5xl">Your way into the room.</h1><p className="mt-3 text-sm text-ink/50">Secure tickets, clear logistics, and one QR code at the door.</p></section>
    {nextTicket ? <section className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="relative overflow-hidden rounded-[24px] bg-ink text-white"><div className="absolute inset-0 opacity-25">{nextTicket.event.coverUrl && <img src={nextTicket.event.coverUrl} alt="" className="size-full object-cover" />}</div><div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/90 to-ink/40" /><div className="relative grid min-h-[390px] gap-8 p-7 sm:grid-cols-[1fr_190px] sm:items-center sm:p-10"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/8 px-3 py-1.5 text-[9px] font-bold"><Ticket size={12} className="text-marigold" />ADMIT {nextTicket.ticket.quantity}</span><p className="eyebrow mt-8 text-marigold">{nextTicket.event.eventType}</p><h2 className="display mt-3 text-5xl font-semibold leading-[.95]">{nextTicket.event.title}</h2><div className="mt-7 grid gap-3 text-xs text-white/60"><span className="flex items-center gap-2"><CalendarDays size={15} className="text-marigold" />{nextTicket.event.startsAt.toLocaleString("en-CM", { dateStyle: "full", timeStyle: "short" })}</span><span className="flex items-center gap-2"><MapPin size={15} className="text-marigold" />{nextTicket.event.venue}, {nextTicket.event.city}</span></div></div><div className="rounded-2xl bg-white p-4 text-ink"><img src={nextTicket.qr} alt={`QR ticket ${nextTicket.ticket.code}`} className="w-full" /><p className="mt-3 text-center text-[9px] font-bold">PRESENT AT ENTRY</p></div></div></article><aside className="rounded-[22px] border border-ink/10 bg-white p-6"><p className="eyebrow text-ink/38">Ticket details</p><div className="mt-5 divide-y divide-ink/10 text-xs"><div className="flex justify-between py-3"><span className="text-ink/45">Holder</span><strong>{session.fullName}</strong></div><div className="flex justify-between py-3"><span className="text-ink/45">Paid</span><strong>{formatXaf(nextTicket.ticket.amount)}</strong></div><div className="flex justify-between py-3"><span className="text-ink/45">Status</span><strong className="text-forest">Valid</strong></div></div><p className="mt-5 flex gap-2 rounded-xl bg-mint/60 p-3 text-[10px] leading-5 text-forest"><ShieldCheck size={14} />Your QR is unique. Do not forward it outside your party.</p></aside></section> : <section className="paper-card mt-8 py-16 text-center"><QrCode className="mx-auto text-ink/25" /><h2 className="display mt-4 text-3xl font-semibold">No tickets yet.</h2><p className="mt-2 text-sm text-ink/50">Find an event and reserve your place.</p><Link href="/client/events" className="btn-ink mt-6">Discover events</Link></section>}
    <section className="mt-12"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow text-berry">Discover public events</p><h2 className="display mt-2 text-3xl font-semibold">More rooms worth entering.</h2></div><Link href="/client/events" className="text-sm font-bold text-berry">See all events</Link></div><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.events.slice(0, 3).map((event) => <article key={event.id} className="overflow-hidden rounded-[20px] border border-ink/10 bg-white"><div className="aspect-[1.7] overflow-hidden">{event.coverUrl && <img src={event.coverUrl} alt={event.title} className="size-full object-cover" />}</div><div className="p-5"><p className="eyebrow text-berry">{event.eventType}</p><h3 className="display mt-2 text-2xl font-semibold">{event.title}</h3><p className="mt-3 text-xs text-ink/48">{event.startsAt.toLocaleDateString("en-CM", { day: "numeric", month: "long" })} · {event.city}</p><p className="mono mt-5 text-xs font-bold">{formatXaf(event.ticketPrice ?? 0)}</p><TicketPurchaseForm eventId={event.id} price={event.ticketPrice ?? 0} /></div></article>)}</div></section>
    <section className="mt-12 rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7"><p className="eyebrow text-berry">Notifications</p><h2 className="display mt-2 text-3xl font-semibold">Stay in the loop.</h2><div className="mt-5 divide-y divide-ink/10">{data.notifications.length ? data.notifications.slice(0, 4).map((notification) => <article key={notification.id} className="py-4"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold">{notification.title}</p><p className="mt-1 text-xs leading-5 text-ink/52">{notification.body}</p></div><time className="mono text-[9px] text-ink/35">{notification.createdAt.toLocaleDateString("en-CM", { day: "numeric", month: "short" })}</time></div></article>) : <p className="py-6 text-sm text-ink/45">You have no notifications yet.</p>}</div></section>
  </DashboardShell>;
}
