import { DashboardShell } from "@/shared/components/dashboard-shell";
import { PageHeading } from "@/shared/components/page-heading";
import { StatusPill, UiState } from "@/shared/components/ui-state";
import { reviewAccessRequest } from "@backend/admin/actions";
import { getAdminData } from "@backend/admin/queries";
import { requireRole } from "@backend/auth/session";
import { Check, Clock3, X } from "lucide-react";
export const dynamic = "force-dynamic";
export default async function AccessRequestsPage() { const session = await requireRole("admin"); const { requests } = await getAdminData(); return <DashboardShell role="admin" name={session.fullName} active="Access requests"><PageHeading eyebrow="Trust review" title="Access requests" description="Review identity documents and issue credentials deliberately. Every decision changes who can enter the marketplace." aside={<StatusPill tone="attention">{requests.filter((item) => item.status === "pending").length} awaiting review</StatusPill>} /><section className="mt-8 max-w-4xl divide-y divide-ink/10 rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7">{requests.length ? requests.map((request) => <article className="flex flex-wrap items-center justify-between gap-4 py-5 first:pt-0" key={request.id}><div><div className="flex items-center gap-2"><p className="font-bold">{request.fullName}</p><StatusPill>{request.desiredRole === "service_provider" ? "Service provider" : request.desiredRole}</StatusPill></div><p className="mt-2 text-xs text-ink/48">{request.email}</p>{request.message && <p className="mt-2 max-w-xl text-xs leading-5 text-ink/52">{request.message}</p>}{request.identityDocumentPath && <a className="mt-3 inline-block text-xs font-bold text-berry underline-offset-4 hover:underline" href={`/api/admin/access-requests/${request.id}/document`} target="_blank" rel="noreferrer">Review identity document</a>}</div>{request.status === "pending" ? <div className="flex gap-2"><form action={reviewAccessRequest}><input type="hidden" name="id" value={request.id}/><input type="hidden" name="decision" value="approved"/><button className="btn-primary !min-h-9 !px-3 text-xs"><Check size={14}/>Approve</button></form><form action={reviewAccessRequest}><input type="hidden" name="id" value={request.id}/><input type="hidden" name="decision" value="rejected"/><button className="btn-secondary !min-h-9 !px-3 text-xs"><X size={14}/>Reject</button></form></div> : <StatusPill tone={request.status === "approved" ? "secure" : "danger"}><Clock3 size={12}/>{request.status}</StatusPill>}</article>) : <UiState title="No requests need review" description="New service provider and organizer access requests will appear here for your trust team." />}</section></DashboardShell>; }
