import { DashboardShell } from "@/shared/components/dashboard-shell";
import { moderateReview } from "@backend/admin/actions";
import { getAdminData } from "@backend/admin/queries";
import { requireRole } from "@backend/auth/session";
import { BellOff, EyeOff, Star } from "lucide-react";

export const dynamic = "force-dynamic";
export default async function PlatformHealthPage() {
  const session = await requireRole("admin"); const { reviews, emailLog } = await getAdminData();
  return <DashboardShell role="admin" name={session.fullName} active="Platform health"><p className="eyebrow text-berry">Quality & delivery</p><h1 className="display mt-2 text-4xl font-semibold">Platform health.</h1><div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow text-berry">Review moderation</p><h2 className="display mt-2 text-3xl font-semibold">Marketplace feedback.</h2></div><Star className="text-marigold"/></div><div className="mt-5 divide-y divide-ink/10">{reviews.length ? reviews.map((review) => <article key={review.id} className="py-4"><div className="flex justify-between gap-3"><p className="text-xs font-bold">{review.rating}/5 rating</p><span className={`text-[9px] font-bold uppercase ${review.isHidden ? "text-berry" : "text-forest"}`}>{review.isHidden ? "Hidden" : "Visible"}</span></div><p className="mt-2 text-xs leading-5 text-ink/55">{review.comment}</p><form action={moderateReview} className="mt-3"><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="hidden" value={review.isHidden ? "false" : "true"}/><button className="btn-secondary !min-h-8 !px-2 text-[9px]"><EyeOff size={12}/>{review.isHidden ? "Restore review" : "Hide review"}</button></form></article>) : <div className="py-12 text-center"><Star className="mx-auto text-ink/25"/><p className="mt-4 text-sm text-ink/50">No reviews yet.</p></div>}</div></section><section className="rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow text-berry">Notification delivery</p><h2 className="display mt-2 text-3xl font-semibold">Email activity.</h2></div><BellOff className="text-berry"/></div><p className="mt-3 text-xs text-ink/50">Delivery attempts are logged here. SMTP transport failures are surfaced in server monitoring until a retry queue is configured.</p><div className="mt-5 divide-y divide-ink/10">{emailLog.length ? emailLog.map((email) => <div key={email.id} className="py-3"><p className="truncate text-xs font-bold">{email.subject}</p><p className="mt-1 truncate text-[10px] text-ink/45">{email.toEmail} · {email.createdAt.toLocaleString("en-CM")}</p></div>) : <div className="py-12 text-center"><BellOff className="mx-auto text-ink/25"/><p className="mt-4 text-sm text-ink/50">No email activity yet.</p></div>}</div></section></div></DashboardShell>;
}
