import { DashboardShell } from "@/shared/components/dashboard-shell";
import { getAdminData } from "@backend/admin/queries";
import { requireRole } from "@backend/auth/session";
import { formatXaf } from "@/shared/lib/format";
import { CalendarDays, CircleAlert } from "lucide-react";

export const dynamic = "force-dynamic";
export default async function AdminBookingsPage() {
  const session = await requireRole("admin"); const { bookings, highRiskBookings } = await getAdminData(); const riskIds = new Set(highRiskBookings.map((booking) => booking.id));
  return <DashboardShell role="admin" name={session.fullName} active="Booking monitor"><p className="eyebrow text-berry">Platform operations</p><h1 className="display mt-2 text-4xl font-semibold">Booking monitor.</h1><p className="mt-3 text-sm text-ink/50">Risk-prioritized platform activity, including disputes, unaccepted requests, overdue events, and high-value holds.</p><section className="mt-8 rounded-[22px] border border-ink/10 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow text-berry">Needs attention</p><h2 className="display mt-2 text-3xl font-semibold">Flagged bookings.</h2></div><span className="rounded-full bg-berry/10 px-3 py-1 text-[10px] font-bold text-berry">{highRiskBookings.length} FLAGGED</span></div><div className="mt-5 divide-y divide-ink/10">{bookings.length ? bookings.map((booking) => <article key={booking.id} className={`flex flex-wrap items-center justify-between gap-4 py-4 ${riskIds.has(booking.id) ? "bg-berry/[0.03]" : ""}`}><div className="flex gap-3"><span className={`mt-1 grid size-8 place-items-center rounded-full ${riskIds.has(booking.id) ? "bg-berry/10 text-berry" : "bg-paper text-ink/40"}`}>{riskIds.has(booking.id) ? <CircleAlert size={15}/> : "·"}</span><div><p className="mono text-xs font-bold">{booking.reference}</p><p className="mt-1 text-[10px] capitalize text-ink/48">{booking.status.replaceAll("_", " ")} · Event {booking.eventDate.toLocaleDateString("en-CM")}</p></div></div><div className="text-right"><p className="mono text-xs font-bold">{formatXaf(booking.fundedAmount)}</p><p className="mt-1 text-[9px] text-ink/38">{booking.createdAt.toLocaleDateString("en-CM")}</p></div></article>) : <div className="py-16 text-center"><CalendarDays className="mx-auto text-ink/25"/><p className="mt-4 text-sm text-ink/50">No bookings yet.</p></div>}</div></section></DashboardShell>;
}
